<?php
/**
 * Created by PhpStorm.
 * User: Greats
 * Date: 6/21/2017
 * Time: 7:55 PM
 */?>

<style>
    th, td {
        padding: 15px;
        text-align: left;
    }
    th {
        background-color: #2b5797;
        color: white;
    }
    th, td {
        border-bottom: 1px solid #ddd;
    }
    tr:hover {background-color: #f5f5f5}
    tr:nth-child(even) {background-color: #4285F4}

    span{
        color: #2b5797;
    }
</style>

<h1 style="color:#2b5797;text-align: center">Koroga Festival</h1>
<h4 style="color:#2b5797;text-align: center">(E-Ticket)</h4>
<p>
<strong style="float: right;color:#2b5797">Date: 27 June 2017 5:00PM</strong>
<strong style="float: leftt;color:#2b5797">Organizer: Capital FM</strong><br>
<hr>
<br>

<table class="striped" style="padding-left: 180px;border-radius: 24px;">
    <tr>
        <th >Serial</th>
        <th >Event Name</th>
        <th >Ticket Fee</th>
        <th >No of Tickets</th>
        <th>Total Cost</th>
        <th >Received Amount</th>
        <th >Date</th>


    </tr>

<!--    --><?php

//        ?>
        <tr>
        <tr>
            <td align="center" valign="bottom">KHg56443</td>
            <td align="center" valign="bottom">Koroga Festival</td>
            <td align="center" valign="bottom">Ksh 2000</td>
            <td align="center" valign="bottom">2</td>
            <td align="center" valign="bottom">Ksh 4000</td>
            <td align="center" valign="bottom">Ksh 4000</td>
            <td align="center" valign="bottom">22 June 2017</td>
        </tr>
    <tr>
        <td align="center" valign="bottom">KHg56443</td>
        <td align="center" valign="bottom">Koroga Festival</td>
        <td align="center" valign="bottom">Ksh 2000</td>
        <td align="center" valign="bottom">2</td>
        <td align="center" valign="bottom">Ksh 4000</td>
        <td align="center" valign="bottom">Ksh 4000</td>
        <td align="center" valign="bottom">22 June 2017</td>
    </tr>
    <?php ?>
</table>


<br><br>
<p style=" color: #2b5797;text-align: center"><small style="text-align: center">Report Generated on: 22 June 2017</small></p>
<p style=" color: #2b5797;text-align: center"><small style="text-align: center">Report Generated by: Ticko Event System by </small></p>
<p style=" color: #2b5797;text-align: center"><small style="text-align: center"><strong>Joseph Nzioka</strong></small></p>
</body>

</html>
